# Generated by Django 4.2.20 on 2025-03-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldlog',
            name='Total_miles_driving_today',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='totle_driving',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='totle_off_duty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='totle_on_duty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='totle_sleeper_berth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='trailer_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='vehicle_number',
            field=models.PositiveIntegerField(),
        ),
    ]
