# Generated by Django 4.2.20 on 2025-03-18 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_log', '0004_alter_eldlog_total_miles_driving_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldlog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
